export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_BARANG = "GET_BARANG";
export const CREATE_BARANG = "CREATE_BARANG";
export const DELETE_BARANG = "DELETE_BANRANG";
export const UPDATE_BARANG = "UPDATE_BANRANG";

export const SET_NAMA_BARANG = "SET_NAMA_BARANG";
export const CLEAR_NAMA_BARANG = "CLEAR_NAMA_BARANG";

export const SET_HARGA_BARANG = "SET_HARGA_BARANG";
export const CLEAR_HARGA_BARANG = "CLEAR_HARGA_BARANG";

export const SET_KATEGORI_BARANG = "SET_KATEGORI_BARANG";
export const CLEAR_KATEGORI_BARANG = "CLEAR_KATEGORI_BARANG";

export const SET_KETERANGAN_BARANG = "SET_KETERANGAN_BARANG";
export const CLEAR_KETERANGAN_BARANG = "CLEAR_KETERANGAN_BARANG";